import java.awt.Cursor;
import java.sql.*;
import javax.swing.*;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author mertk
 */
public class Movies extends javax.swing.JInternalFrame {

    /**
     * Creates new form Movies
     */
    public Movies() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui =(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        LoadButton = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Remove = new javax.swing.JButton();
        RemoveText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        MovieNameAdder = new javax.swing.JTextField();
        SoundtrackAdder = new javax.swing.JTextField();
        ReleaseYearAdder = new javax.swing.JTextField();
        PlotAdder = new javax.swing.JTextField();
        BudgetAdder = new javax.swing.JTextField();
        CompanyNameAdder = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        choice1 = new java.awt.Choice();

        jButton1.setText("jButton1");

        jButton3.setText("jButton3");

        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(1200, 744));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(1002, 744));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("My Movie List");

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Movie Name", "Soundtrack", "Release Year", "Plot", "Budget", "Company Name"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        LoadButton.setBackground(new java.awt.Color(0, 0, 0));
        LoadButton.setForeground(new java.awt.Color(255, 255, 255));
        LoadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-load-24 (1).png"))); // NOI18N
        LoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadButtonActionPerformed(evt);
            }
        });

        AddButton.setBackground(new java.awt.Color(0, 0, 0));
        AddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-add-24.png"))); // NOI18N
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        Update.setBackground(new java.awt.Color(0, 0, 0));
        Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-update-24.png"))); // NOI18N
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Remove.setBackground(new java.awt.Color(0, 0, 0));
        Remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-remove-24.png"))); // NOI18N
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });

        RemoveText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(LoadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RemoveText, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoadButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AddButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Update, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Remove, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RemoveText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        MovieNameAdder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovieNameAdderActionPerformed(evt);
            }
        });

        SoundtrackAdder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoundtrackAdderActionPerformed(evt);
            }
        });

        ReleaseYearAdder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReleaseYearAdderActionPerformed(evt);
            }
        });

        PlotAdder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlotAdderActionPerformed(evt);
            }
        });

        BudgetAdder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BudgetAdderActionPerformed(evt);
            }
        });

        CompanyNameAdder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompanyNameAdderActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Movie Name");

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Soundtrack");

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Plot");

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Release Year");

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Budget");

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Company Name");

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Plot");

        choice1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        choice1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                choice1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(26, 26, 26)
                                .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(MovieNameAdder, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SoundtrackAdder, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(ReleaseYearAdder, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel6))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(BudgetAdder, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addComponent(jLabel5))
                            .addComponent(PlotAdder, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(CompanyNameAdder, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MovieNameAdder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SoundtrackAdder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addGap(12, 12, 12)
                        .addComponent(ReleaseYearAdder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PlotAdder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BudgetAdder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CompanyNameAdder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1188, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void choice1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choice1MouseClicked
    choice1.removeAll(); // Clear existing choices

    choice1.addItem("Action");
    choice1.addItem("Sci-fi");
    choice1.addItem("Horror");
    choice1.addItem("Animation");
    choice1.addItem("Romance");
    choice1.addItem("Comedy");
    choice1.addItem("Drama");
    choice1.addItem("Fantasy");
    choice1.addItem("Thriller");
    choice1.addItem("Romantic Comedy");
    choice1.addItem("Adventure");
    choice1.addItem("Narrative");
    choice1.addItem("Anime");
    choice1.addItem("History");
    
    

    jPanel2.revalidate(); // Refresh the panel to update the UI
    }//GEN-LAST:event_choice1MouseClicked

    private void LoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadButtonActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mms", "root", "!!mert3!!");
            java.sql.Statement st = conn.createStatement();

            String plot1 = choice1.getSelectedItem(); // Get the selected genre from choice1
           

            // Construct the SQL query with the selected filters
            String sql = "SELECT * FROM movie WHERE 1=1";

            if (plot1 != null && !plot1.isEmpty()) {
                sql += " AND Plot = '" + plot1 + "'";
            }

            

            ResultSet rs = st.executeQuery(sql);

            // Clear existing table data
            DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
            tblModel.setRowCount(0);

            while (rs.next()) {
                String movieName = rs.getString("MovieName");
                String soundtrack = rs.getString("SoundTrack");
                String releaseYear = rs.getString("ReleaseYear");
                String plot = rs.getString("Plot");
                String budget = String.valueOf(rs.getInt("Budget"));
                String companyName = rs.getString("CompanyName");

                String tbData[] = { movieName, soundtrack, releaseYear, plot, budget, companyName };
                tblModel.addRow(tbData);
            }

}catch(Exception e){
             System.out.println(e.getMessage());
       
}

    }//GEN-LAST:event_LoadButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
         try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mms", "root", "!!mert3!!");
        java.sql.Statement st = conn.createStatement();

        // Get the data entered by the user
        String movieName = MovieNameAdder.getText(); // Assuming you have a jTextField1 for Movie Name input
        String soundtrack = SoundtrackAdder.getText(); // Assuming you have a jTextField2 for Soundtrack input
        String releaseYear = ReleaseYearAdder.getText(); // Assuming you have a jTextField3 for Release Year input
        String plot = PlotAdder.getText(); // Assuming you have a jTextField4 for Plot input
        String budget = BudgetAdder.getText(); // Assuming you have a jTextField5 for Budget input
        String companyName = CompanyNameAdder.getText(); // Assuming you have a jTextField6 for Company Name input

        // Construct the SQL query to insert the data into the database
        String sql = "INSERT INTO movie (MovieName, SoundTrack, ReleaseYear, Plot, Budget, CompanyName) VALUES ('"
                + movieName + "', '" + soundtrack + "', '" + releaseYear + "', '" + plot + "', " + budget + ", '"
                + companyName + "')";

        // Execute the SQL query to insert the data
        int rowsAffected = st.executeUpdate(sql);

        if (rowsAffected > 0) {
            // Data inserted successfully
            System.out.println("Data inserted successfully");
            // You can also show a success message to the user or perform any other desired actions
        } else {
            // Failed to insert data
            System.out.println("Failed to insert data");
            // You can show an error message to the user or perform any other desired actions
        }

        // Close the database connection
        conn.close();
        
}catch(Exception e){
             System.out.println(e.getMessage());
       
}
    }//GEN-LAST:event_AddButtonActionPerformed

    private void ReleaseYearAdderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReleaseYearAdderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReleaseYearAdderActionPerformed

    private void MovieNameAdderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovieNameAdderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MovieNameAdderActionPerformed

    private void PlotAdderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlotAdderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlotAdderActionPerformed

    private void BudgetAdderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BudgetAdderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BudgetAdderActionPerformed

    private void CompanyNameAdderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompanyNameAdderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompanyNameAdderActionPerformed

    private void SoundtrackAdderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoundtrackAdderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoundtrackAdderActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mms","root","!!mert3!!");
            Statement st = con.createStatement();
         int r = JOptionPane.showConfirmDialog(this,"You are going to update this movie data!!");
         if(r==0){
               Boolean b= st.execute("UPDATE Movie set Soundtrack= '"+ SoundtrackAdder.getText()+"',ReleaseYear='"+ReleaseYearAdder.getText()+"',Plot='"+PlotAdder.getText()+"', Budget ='"+BudgetAdder.getText()+"',CompanyName='"+CompanyNameAdder.getText()+"'where  MovieName='"+MovieNameAdder.getText()+"'");

           if(!b)
               JOptionPane.showMessageDialog(this,"Updated");
           else
               JOptionPane.showMessageDialog(this, "Something wrong");
         }
               
            con.close();

        }catch(Exception e){
            System.out.println(e.getMessage());
        }


    }//GEN-LAST:event_UpdateActionPerformed

    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
        try {
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/mms", "root", "!!mert3!!");
            
            String sql = "DELETE FROM mms.movie WHERE MovieName = ? ";
            PreparedStatement ps = connection.prepareStatement(sql);
            ps.setString(1, RemoveText.getText());
            
            ps.executeUpdate();
            ps.close();
            connection.close();
}catch(Exception e){
             System.out.println(e.getMessage());
       
}

    }//GEN-LAST:event_RemoveActionPerformed

    private void RemoveTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemoveTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JTextField BudgetAdder;
    private javax.swing.JTextField CompanyNameAdder;
    private javax.swing.JButton LoadButton;
    private javax.swing.JTextField MovieNameAdder;
    private javax.swing.JTextField PlotAdder;
    private javax.swing.JTextField ReleaseYearAdder;
    private javax.swing.JButton Remove;
    private javax.swing.JTextField RemoveText;
    private javax.swing.JTextField SoundtrackAdder;
    private javax.swing.JButton Update;
    private java.awt.Choice choice1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
